/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 first_person_hands_rigged.glb 
Author: DavidFischer (https://sketchfab.com/davidfischer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/first-person-hands-rigged-547a45535f0c4fe787948f7a7a6a88db
Title: First Person hands rigged
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/first_person_hands_rigged.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh geometry={nodes.Object_7.geometry} material={materials['basicRigSkin.001']} skeleton={nodes.Object_7.skeleton} />
        <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.basicRigSkin} skeleton={nodes.Object_8.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/first_person_hands_rigged.glb')
