/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 hand_gesture_1.glb 
Author: flioink (https://sketchfab.com/flioink)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hand-gesture-1-97874dad2e67473e8299b5230766afd8
Title: Hand_gesture_1
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hand_gesture_1.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Hand_gesture_1initialShadingGroup} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Hand_gesture_1initialShadingGroup} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Hand_gesture_1initialShadingGroup} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Hand_gesture_1initialShadingGroup} />
      </group>
    </group>
  )
}

useGLTF.preload('/hand_gesture_1.glb')
