/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rigged_hand.glb 
Author: Elena FF (https://sketchfab.com/elenaferfor)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/rigged-hand-eae97cc2a742413cb5338ab942b12c1e
Title: Rigged hand
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/rigged_hand.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.015}>
          <group name="f02ee8bcd0644bfa96313f17aa2cca59fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Light" position={[407.625, 590.386, -100.545]} rotation={[1.89, 0.881, -2.045]} scale={100}>
                  <group name="Object_5" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_6" />
                  </group>
                </group>
                <group name="Camera" position={[735.889, 495.831, 692.579]} rotation={[Math.PI, 0.756, 2.68]} scale={100}>
                  <group name="Object_8" />
                </group>
                <group name="handSmooth001" position={[-19.168, 79.78, 66.557]} rotation={[-1.447, -0.594, 0.604]} scale={100} />
                <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_11">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_13" position={[-19.168, 79.78, 66.557]} rotation={[-1.447, -0.594, 0.604]} scale={100} />
                    <skinnedMesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.lambert1} skeleton={nodes.Object_14.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/rigged_hand.glb')
